services:
  product.services:
    container_name: product.service
    build: ./Product.Service
    networks:
      - my-api-payment
    ports:
      - "5010:5010"
    environment:
      - APIPORT=5010
      - DB_HOST=${DB_HOST_PRODUCT}
      - DB_PORT=${DB_PORT_PRODUCT}
      - DB_NAME=${DB_NAME_PRODUCT}
      - DB_USER=${DB_USER_PRODUCT}
      - DB_PASSWORD=${DB_PASSWORD_PRODUCT}

  order.services:
    container_name: order.service
    build: ./Order.Service
    networks:
      - my-api-payment
    ports:
      - "5011:5011"
    environment:
      - APIPORT=5011
      - DB_HOST=${DB_HOST_ORDER}
      - DB_PORT=${DB_PORT_ORDER}
      - DB_NAME=${DB_NAME_ORDER}
      - DB_USER=${DB_USER_ORDER}
      - DB_PASSWORD=${DB_PASSWORD_ORDER}

  payment.services:
    container_name: payment.service
    build: ./Payment.Service
    networks:
      - my-api-payment
    ports:
      - "5013:5013"
    environment:
      - APIPORT=5013
      # Aqui você pode fazer igual se quiser ou deixar fixo

networks:
  my-api-payment:
    driver: bridge
