name: Deploy Services to Railway

on:
  push:
    branches:
      - master

jobs:
  deploy-product:
    name: Deploy Product Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - List root directory
        run: ls -la

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Add Railway to PATH
        run: echo "${HOME}/.railway/bin" >> $GITHUB_PATH

      - name: Deploy Product Service to Railway
        working-directory: ./Product.Service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service product

  deploy-order:
    name: Deploy Order Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - List root directory
        run: ls -la

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Add Railway to PATH
        run: echo "${HOME}/.railway/bin" >> $GITHUB_PATH

      - name: Deploy Order Service to Railway
        working-directory: ./Order.Service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service order

  deploy-payment:
    name: Deploy Payment Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - List root directory
        run: ls -la

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Add Railway to PATH
        run: echo "${HOME}/.railway/bin" >> $GITHUB_PATH

      - name: Deploy Payment Service to Railway
        working-directory: ./Payment.Service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service payment

  deploy-apigateway:
    name: Deploy API Gateway (Ocelot)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - List root directory
        run: ls -la

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Add Railway to PATH
        run: echo "${HOME}/.railway/bin" >> $GITHUB_PATH

      - name: Deploy API Gateway to Railway
        working-directory: ./ApiGateway.Ocelot
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service api-gateway
