name: Deploy Services to Railway

on:
  push:
    branches:
      - master

jobs:
  deploy-product:
    name: Deploy Product Service
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        SVC_ID: product
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Product Service to Railway
        working-directory: ./Product.Service
        run: railway up --service=${{ env.SVC_ID }}

  deploy-order:
    name: Deploy Order Service
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        SVC_ID: order
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Order Service to Railway
        working-directory: ./Order.Service
        run: railway up --service=${{ env.SVC_ID }}

  deploy-payment:
    name: Deploy Payment Service
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        SVC_ID: payment
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Payment Service to Railway
        working-directory: ./Payment.Service
        run: railway up --service=${{ env.SVC_ID }}

  deploy-apigateway:
    name: Deploy API Gateway (Ocelot)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        SVC_ID: api-gateway
    steps:
      - uses: actions/checkout@v3

      - name: Deploy API Gateway to Railway
        working-directory: ./ApiGateway.Ocelot
        run: railway up --service=${{ env.SVC_ID }}
