name: Deploy Services to Railway

on:
  push:
    branches:
      - master
      - test-ci-cd

jobs:
  deploy-product:
    name: Deploy Product Service
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: List workspace root
        run: ls -la

      - name: List Product.Service folder
        run: ls -la Product.Service || echo "Folder not found"

      - name: Deploy Product Service to Railway
        run: |
          cd Product.Service
          railway up --service=product

  deploy-order:
    name: Deploy Order Service
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: List workspace root
        run: ls -la

      - name: List Order.Service folder
        run: ls -la Order.Service || echo "Folder not found"

      - name: Deploy Order Service to Railway
        run: |
          cd Order.Service
          railway up --service=order

  deploy-payment:
    name: Deploy Payment Service
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: List workspace root
        run: ls -la

      - name: List Payment.Service folder
        run: ls -la Payment.Service || echo "Folder not found"

      - name: Deploy Payment Service to Railway
        run: |
          cd Payment.Service
          railway up --service=payment

  deploy-apigateway:
    name: Deploy API Gateway (Ocelot)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: List workspace root
        run: ls -la

      - name: List ApiGateway.Ocelot folder
        run: ls -la ApiGateway.Ocelot || echo "Folder not found"

      - name: Deploy API Gateway to Railway
        run: |
          cd ApiGateway.Ocelot
          railway up --service=api-gateway
