name: CI/CD Microservices Railway

on:
  push:
    branches:
      - test-ci-cd

jobs:
  deploy-product:
    if: contains(github.event.head_commit.message, 'Product.Service') || startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Debug - List Product Folder
        run: ls -la Product.Service

      - name: Deploy Product Service to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd Product.Service
          railway up --service product

  deploy-order:
    if: contains(github.event.head_commit.message, 'Order.Service') || startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Debug - List Order Folder
        run: ls -la Order.Service

      - name: Deploy Order Service to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd Order.Service
          railway up --service order

  deploy-payment:
    if: contains(github.event.head_commit.message, 'Payment.Service') || startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Debug - List Payment Folder
        run: ls -la Payment.Service

      - name: Deploy Payment Service to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd Payment.Service
          railway up --service payment

  deploy-api-gateway:
    if: contains(github.event.head_commit.message, 'ApiGateway.Ocelot') || startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Debug - List API Gateway Folder
        run: ls -la ApiGateway.Ocelot

      - name: Deploy API Gateway to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd ApiGateway.Ocelot
          railway up --service api-gateway
